version: '3.5'
services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - "5432:5432"
    scheduler:
        image: apache/airflow:2.0.0-python3.8
        entrypoint: ./scripts/entrypoint.sh
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./:/opt/airflow
    webserver:
        image: apache/airflow:2.0.0-python3.8
        command: webserver
        deploy:
            restart_policy:
                condition: on-failure
        depends_on:
            - postgres
            - scheduler
        env_file:
            - .env
        volumes:
            - ./:/opt/airflow
        ports:
            - "8080:8080"